---
prices:
  -
    code: ebooks
    name: "HTML & eBook"
    description:
      |
        * DRM-free copies of the ebooks in EPUB, MOBI, and PDF formats
        * Over 2 pages of content (and growing!)
    media:
      - ebooks
    price: 3900

  -
    code: all
    name: "HTML, eBook, and Screencasts"
    description:
      |
        * The full screencast series
        * xy screencast lessons (one for each chapter), with more than xy hours of downloadable HD video (see the teaser trailer or view a free sample lesson)
        * DRM-free copies of the ebooks in EPUB, MOBI, and PDF formats
        * Over 2 pages of content (and growing!)
    media:
      - ebooks
      - media/screencasts
    price: 14900

authors:
  -
    name: "Knight of the Old Code"
    image: /images/testimonial_1.png
    contact_email: "info@knightoftheoldcode.com"
    contact_twitter: "@knightotoldcode"
    contact_gh: "@knightoftheoldcode"
    bio:
      |
         [Knight of the Old Code](https://knightoftheoldcode/) is a team of dedicated web developers interested in
         teaching web development using modern technologies and techniques.

faq:
  -
    question: "Have a question? Please contact us and ask it."
    answer: "...We will collect the common ones and answer them here."

  -
    question: "Have a question? Please contact us and ask it."
    answer: "...We will collect the common ones and answer them here."

testimonials:
  -
    name: "Merlin Ambrosius"
    title: "Principle Mythical Advisor to King Arthur Pendragon"
    image: /images/testimonial_merlin.jpg
    text: "I got review access to all of the material and can confirm that, yes, these screencasts are magical… If you basically want to be able to peer 'over the shoulder' of an experienced web developer and see how a modern development environment is set up and how apps are built, there’s nothing that can beat this. This isn’t a set of 'build a blog in 15 minutes' videos—it’s a complete 'build a blog in 15 days' course that could kick off a new career for you with JavaScript. [Snarky little wizard!]"

  -
    name: "Arthur Pendragon"
    title: "King of Camelot"
    image: /images/testimonial_arthur.jpg
    text: "Verily I say unto thee: goest forth and purchase these tomes of great value. Camelot used to be 'behind the times' at all the political events, but now we are at the forefront of the intersection of wizardry and technology. Please visit our website and sign our guestbook! [There is no mention of a guestbook feature in the tutorial...we can only assume that feature request was submitted to the camelot development team by Morgana le Fay.]"

marketing_content: ''

repo_url: ''
contact_email: ''
hide_custom_domain_footer: false
